name: Main Build

on:
  push:
    branches:
      - main
    paths:
      - '**/src/**'
      - '**/tests/**'      
      - '**/.github/**'
  pull_request:
    branches: [ main ]

  workflow_dispatch:
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore      
   
    - name: Test
      run: |
        dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage        
   
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
        
    - name: Write to Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
    
    - name: DotNet Coverage
      run: |
        dotnet tool install --global dotnet-coverage  
        dotnet build src --no-incremental
        cd src
        dotnet-coverage collect 'dotnet test' -f xml -o 'coverage.xml'            
      
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      with:
        projectBaseDir: src
        args: >
          -Dsonar.organization=kellysonrn
          -Dsonar.coverage.jacoco.xmlReportPaths=./src/coverage.xml
          -Dsonar.projectKey=KellysonRN_code-quality-labs
          -Dsonar.projectBaseDir=.
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} 
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}  
       
