name: Build

on:
  push:
    branches:
      - main
    paths:
      - '**/src/**'
      - '**/tests/**'      
      - '**/.github/**'
  pull_request:
    branches: [ main ]

  workflow_dispatch:
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Setup DotNet Coverage
      run: |        
        dotnet tool install --global dotnet-sonarscanner
        dotnet tool update dotnet-reportgenerator-globaltool -g

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore      
   
    - name: Test
      run: |
        dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage              
      
    - name: PR Metrics
      uses: microsoft/PR-Metrics@v1.5.0
      env:
        PR_METRICS_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        base-size: 200
        growth-rate: 2.0
        test-factor: 1.0
        file-matching-patterns: |
          **/*
          !Ignore.cs
        code-file-extensions: |
          cs
          ps1
      continue-on-error: true


        

